name: "Builds README.md"
description: "Builds README.md from jupyter notebook"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install Requirements
      run: pip install -r requirements.txt
      shell: bash
    - name: Build README.md
      run: |
        jupyter nbconvert --to Markdown pd_project.ipynb
        python processReadMe.py
        rm pd_project.md
      shell: bash
    - name: Commit & Push changes
      run: |
        git config --global user.name "xImouto"
        git config --global user.email "mohammad.rafid.hamid@g.bracu.ac.bd"
        git add README.md
        git commit -m "built readme"
        git push origin main
      shell: bash
